---
- name: Collect IOS Information and Configure Logging
  hosts: your_router_hostname
  gather_facts: true
  tasks:
    - name: Collect IOS Version Information
      ios_facts:
      register: ios_version_info

    - name: Display IOS Version Information
      debug:
        var: ios_version_info

    - name: Collect L3 Interface Information
      ios_facts:
        gather_subset: interfaces
      register: l3_interface_info

    - name: Display L3 Interface Information
      debug:
        var: l3_interface_info

    - name: Configure Logging Buffer
      ios_logging_resource:
        buffer_size: 5000